# Generated by Django 5.1.1 on 2025-03-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_name', models.CharField(max_length=100, unique=True)),
                ('hospital_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
