# Generated by Django 5.2.3 on 2025-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_hospital_ip_addr_hospital_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
    ]
