# Generated by Django 5.0.7 on 2025-03-08 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('confirm_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('username', 'password')},
        ),
    ]
