# Generated by Django 5.0.7 on 2025-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverForm', '0002_user_driver_username_alter_driver_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
