# Generated by Django 5.1.1 on 2025-03-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverForm', '0003_remove_user_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
